#pragma once

#include <cstdint>
#include <vector>

namespace penrose {

// =============================================================================
// Tile data model
// =============================================================================
// A single tile, polymorphic across the families:
//   P3 / P2      — Robinson triangles. verts = [A, B, C] with B = apex,
//                  A-C base. type = 0 (L = obtuse 108-36-36) or
//                  1 (S = acute 36-72-72).
//   Chair        — L-tromino. 6 vertices in CCW order. type = 0..3, the
//                  integer orientation (also used by the "type" color mode).
//   Dodecagonal  — de Bruijn rhombus. 4 vertices in CCW order. type = 0..2,
//                  the rhomb shape (0 = 30 thin, 1 = 60 thick, 2 = 90 square).
//   Pinwheel     — Conway/Radin 1:2:sqrt(5) right triangle. verts = [S, L, M],
//                  the small (~26.57 deg), right (90 deg) and medium-angle
//                  corners. type = 0/1 chirality (mirror image or not).
// We pack every shape into the same struct so the renderer can iterate
// uniformly. `vcount` is 3 for Penrose / pinwheel, 4 for dodecagonal,
// 6 for Chair.
// =============================================================================

struct Tile {
    float x[6];
    float y[6];
    uint8_t vcount;   // 3 for P3/P2/pinwheel tris, 4 for dodeca rhombs, 6 chair
    uint8_t type;     // 0=L,1=S Penrose; 0..3 chair; 0..2 dodeca; 0/1 pinwheel
};

enum class Family : int { P3 = 0, P2 = 1, Chair = 2, Dodecagonal = 3, Pinwheel = 4 };

// Number of Family enumerators. The JNI layer validates the incoming family
// index against this; keep it in step with the enum above.
constexpr int kFamilyCount = 5;

// Per-family edge classification used by the border seam-hiding rule.
//   For Penrose: Leg = the two equal-length sides, Base = the third.
//   For Chair / Dodecagonal: ChairEdge — no internal seams to hide.
enum class EdgeKind : uint8_t { Leg = 0, Base = 1, ChairEdge = 2 };

struct Edge {
    float p1x, p1y;
    float p2x, p2y;
    EdgeKind kind;
    uint8_t  tileType; // tile that produced this edge (for hideSeam)
};

// =============================================================================
// Seeds
// =============================================================================

enum class SeedP3 : int { Sun = 0, Star = 1, Cartwheel = 2, Ace = 3 };
enum class SeedP2 : int { Sun = 0, Star = 1 };
enum class SeedChair : int { Pinwheel = 0, Small = 1, Large = 2 };
enum class SeedDodeca : int { Rosette = 0, Drift = 1, Quasi = 2 };
enum class SeedPinwheel : int { Square = 0, Triangle = 1, Rectangle = 2 };

std::vector<Tile> seedP3(SeedP3 seed);
std::vector<Tile> seedP2(SeedP2 seed);
std::vector<Tile> seedChair(SeedChair seed);
std::vector<Tile> seedPinwheel(SeedPinwheel seed);

// =============================================================================
// Substitutions
// =============================================================================

std::vector<Tile> subdivideP3(const std::vector<Tile>& in);
std::vector<Tile> subdivideP2(const std::vector<Tile>& in);
std::vector<Tile> subdivideChair(const std::vector<Tile>& in);

// Pinwheel deflation: each 1:2:sqrt(5) triangle becomes five at 1/sqrt(5)
// scale (Conway / Radin). Reflected tiles arise naturally and are kept.
std::vector<Tile> subdividePinwheel(const std::vector<Tile>& in);

// Dodecagonal is generated by de Bruijn 6-grid dualization, not by a
// substitution: there is no seed/subdivide pair. `generations` selects the
// multigrid line-index range, so a higher value yields a finer patch the
// same way deeper deflation does for the substitution families.
std::vector<Tile> generateDodecagonal(int seedIdx, int generations);

// =============================================================================
// Edge extraction (one entry per side of every tile)
// =============================================================================

// Pushes the 3 edges of a Penrose triangle: A-B (leg), B-C (leg), A-C (base).
void edgesPenrose(const Tile& t, std::vector<Edge>& out);

// Pushes one edge per side of a closed polygon tile, walking `vcount`
// vertices in order — the 6 sides of a chair L-tromino or the 4 sides of a
// dodecagonal rhombus.
void edgesChair(const Tile& t, std::vector<Edge>& out);

// =============================================================================
// Convenience
// =============================================================================

// Per-family hard caps. Chair's 4× growth is much faster than Penrose's phi²;
// keep tile count under ~64k at the cap so on-device generation stays snappy.
constexpr int kMaxGenP3 = 8;
constexpr int kMaxGenP2 = 8;
constexpr int kMaxGenChair = 7;
constexpr int kMaxGenDodeca = 8;
// Pinwheel grows 5x per generation — cap so the square seed stays near ~64k.
constexpr int kMaxGenPinwheel = 6;

// Generate a full tiling: seed + N deflations. Family-erased entry point.
std::vector<Tile> generate(Family family, int seedIdx, int generations);

// Family-aware deflation rate, used by the renderer to skip borders when
// edges shrink below sub-pixel.
inline float deflationRate(Family f) {
    switch (f) {
        case Family::Chair:    return 0.5f;                 // 1/2
        case Family::Pinwheel: return 0.4472135954999579f;  // 1/sqrt(5)
        default:               return 0.6180339887498949f;  // 1/phi
    }
}

} // namespace penrose
